apiVersion: v1
kind: Pod
metadata:
  name: sample-netcore
spec:
  containers:
    - image: docker.io/167235042/sample-netcore
      name: sample-netcore
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 8080